# https://github.com/encode/uvicorn/pull/515/files
# https://github.com/encode/uvicorn/issues/511
# https://github.com/encode/uvicorn/issues/491

version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": cortex.lib.log.CortexFormatter
    format: "%(asctime)s:cortex:pid-%(process)d:%(levelname)s:%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S.%f"
  access:
    "()": cortex.lib.log.CortexAccessFormatter
    format: "%(asctime)s:cortex:pid-%(process)d:%(levelname)s:%(status_code)s %(method)s %(path)s"
    datefmt: "%Y-%m-%d %H:%M:%S.%f"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
